kind: pipeline
name: default

steps:
  - name: build
    image: node:10-alpine
    environment:
      PE_GRAPHQL_API: https://camerabag.sklirg.io/graphql
      PE_MAPBOX_API_TOKEN: $$PE_MAPBOX_API_TOKEN
    commands:
      - yarn
      - yarn build

  - name: lint
    image: node:10-alpine
    commands:
      - yarn elm-analyse

  - name: publish
    image: plugins/s3
    when:
      branch:
        - master
      event:
        - push
    settings:
      bucket: picturelm
      region: eu-central-1
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: dist/**/*
      target: /
      acl: public-read
      strip_prefix: dist/
