-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gallery.Object exposing (GalleryNode(..), GalleryNodeConnection(..), GalleryNodeEdge(..), ImageNode(..), ImageNodeConnection(..), ImageNodeEdge(..), PageInfo(..))


type GalleryNode
    = GalleryNode


type GalleryNodeConnection
    = GalleryNodeConnection


type GalleryNodeEdge
    = GalleryNodeEdge


type ImageNode
    = ImageNode


type ImageNodeConnection
    = ImageNodeConnection


type ImageNodeEdge
    = ImageNodeEdge


type PageInfo
    = PageInfo
